name: Enthusiasms
tagline: Christina Koch's blog
markdown: kramdown
permalink: /:year/:month/:day/:title
root: https://christinalk.github.io/blog-test
baseurl: /blog-test
origin: https://christinalk.github.io
