name: Enthusiasms
tagline: Christina Koch's blog
markdown: kramdown
permalink: /blog-test/:year/:month/:day/:title
root: https://christinalk.github.io/blog-test
baseurl: https://christinalk.github.io/blog-test
origin: https://christinalk.github.io
